"use client";
import { useEffect, useState } from "react";
import { Outfit, Ovo } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import "./globals.css";
import { ThemeProvider } from "@/components/hooks/ThemeContext"; // Import ThemeProvider
import StairTransition from "@/components/StairTransition";
import PageTransition from "@/components/PageTransition";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const ovo = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

// export const metadata = {
//   title: "Hello - Gia Bao",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.className} ${ovo.className} antialiased leading-8 overflow-x-hidden dark:bg-grayTheme dark:text-white`}
      >
        <ThemeProvider>
          <StairTransition />
          <NavBar />
            <PageTransition>
              
                {children}
              <Footer />
            </PageTransition>
        </ThemeProvider>
      </body>
    </html>
  );
}
